### PR TITLE
Add share prefix on advanced spatial extensions

### PR DESCRIPTION
**Pull request by vdelacruzb**
This PR consist mostly in some renaming on the shares and should be merged at the same time that:
https://github.com/CartoDB/carto-advanced-spatial-extension/pull/82

### CODE REVIEW

**Review by Jesus89 — APPROVED** [review]
LGTM

Could you add `export SF_SHARE_PREFIX=""` to the dev_env.sh.sample file after `SF_SCHEMA_PREFIX`?

**Comment by Jesus89** [comment]
I see this log in the deploy-sf job:

```
Share '"SXA81489.SPATIAL_EXTENSIONS"' does not exist or not authorized.
002003 (02000): SQL compilation error:
Share '"SXA81489.SPATIAL_EXTENSIONS"' does not exist or not authorized.
002003 (02000): SQL compilation error:
```

What does it mean?

**Comment by vdelacruzb** [comment]
> I see this log in the deploy-sf job:
> 
> ```
> Share '"SXA81489.SPATIAL_EXTENSIONS"' does not exist or not authorized.
> 002003 (02000): SQL compilation error:
> Share '"SXA81489.SPATIAL_EXTENSIONS"' does not exist or not authorized.
> 002003 (02000): SQL compilation error:
> ```
> 
> What does it mean?

Are you

**Comment by vdelacruzb** [comment]
> I see this log in the deploy-sf job:
> 
> ```
> Share '"SXA81489.SPATIAL_EXTENSIONS"' does not exist or not authorized.
> 002003 (02000): SQL compilation error:
> Share '"SXA81489.SPATIAL_EXTENSIONS"' does not exist or not authorized.
> 002003 (02000): SQL compilation error:
> ```
> 
> What does it mean?

This was happening because staging was trying to grant usage on the share of Production whose owner is the role ACCOUNTADMIN. I've just added a different prefix on staging. On going to reset the production share so the owner is sysadmin and we avoid possible errors when deploying to production. Another possibility would be to add "USE ROLE ACCOUNTADMIN" in every SHARE_CREATE but will give us problems when deploying locally us normally our accounts doesn't have this role.

**Review by Jesus89 — APPROVED** [review]

**Review by alex-graciano — APPROVED** [review]
